// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqwskJY65zlKlUyt3-LjLmCS7u9tlwr0',
    appId: '1:1045584281128:web:008c9a7ea8a674c4a93f1d',
    messagingSenderId: '1045584281128',
    projectId: 'lahv-7d5b6',
    authDomain: 'lahv-7d5b6.firebaseapp.com',
    storageBucket: 'lahv-7d5b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu_cs4sdQFFUWKoCbgxdBCuWdjaxexos4',
    appId: '1:1045584281128:android:96ac07f781aee6c7a93f1d',
    messagingSenderId: '1045584281128',
    projectId: 'lahv-7d5b6',
    storageBucket: 'lahv-7d5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUU5uGaXBBToOy8J-E5YASIxK7VhIg9sQ',
    appId: '1:1045584281128:ios:013086554f84259da93f1d',
    messagingSenderId: '1045584281128',
    projectId: 'lahv-7d5b6',
    storageBucket: 'lahv-7d5b6.firebasestorage.app',
    iosBundleId: 'com.lahv.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUU5uGaXBBToOy8J-E5YASIxK7VhIg9sQ',
    appId: '1:1045584281128:ios:5d2d63ddcf1f6918a93f1d',
    messagingSenderId: '1045584281128',
    projectId: 'lahv-7d5b6',
    storageBucket: 'lahv-7d5b6.firebasestorage.app',
    iosBundleId: 'com.example.laebunVaLahv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfqwskJY65zlKlUyt3-LjLmCS7u9tlwr0',
    appId: '1:1045584281128:web:fa639e546ecefb49a93f1d',
    messagingSenderId: '1045584281128',
    projectId: 'lahv-7d5b6',
    authDomain: 'lahv-7d5b6.firebaseapp.com',
    storageBucket: 'lahv-7d5b6.firebasestorage.app',
  );
}
